// <auto-generated />
using System;
using MemoryService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace MemoryService.Infrastructure.Migrations
{
    [DbContext(typeof(MemoryDbContext))]
    [Migration("20260507124837_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "memory_type", new[] { "fact", "preference", "opinion", "event" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MemoryService.Core.Domain.Memory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Aspect")
                        .HasColumnType("text")
                        .HasColumnName("aspect");

                    b.Property<float>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0.7f)
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Object")
                        .HasColumnType("text")
                        .HasColumnName("object");

                    b.Property<string>("Predicate")
                        .HasColumnType("text")
                        .HasColumnName("predicate");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<Guid>("SourceTurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_turn_id");

                    b.Property<string>("Stance")
                        .HasColumnType("text")
                        .HasColumnName("stance");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid?>("Supersedes")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("Type")
                        .HasColumnType("memory_type")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("memories_embedding_hnsw")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 64)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SessionId");

                    b.HasIndex("SourceTurnId");

                    b.HasIndex("Subject")
                        .HasDatabaseName("memories_subject_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Subject"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Subject"), new[] { "gin_trgm_ops" });

                    b.HasIndex("UserId", "Active")
                        .HasDatabaseName("memories_user_active");

                    b.ToTable("memories", (string)null);
                });

            modelBuilder.Entity("MemoryService.Core.Domain.MemoryEdge", b =>
                {
                    b.Property<Guid>("SrcMemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("src_memory_id");

                    b.Property<string>("Relation")
                        .HasColumnType("text")
                        .HasColumnName("relation");

                    b.Property<Guid>("DstMemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("dst_memory_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SrcMemoryId", "Relation", "DstMemoryId");

                    b.HasIndex("DstMemoryId", "Relation")
                        .HasDatabaseName("memory_edges_dst");

                    b.ToTable("memory_edges", (string)null);
                });

            modelBuilder.Entity("MemoryService.Core.Domain.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("sessions_user");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("MemoryService.Core.Domain.Turn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("messages");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Timestamp")
                        .HasDatabaseName("turns_session");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("turns_user");

                    b.ToTable("turns", (string)null);
                });

            modelBuilder.Entity("MemoryService.Core.Domain.Memory", b =>
                {
                    b.HasOne("MemoryService.Core.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoryService.Core.Domain.Turn", null)
                        .WithMany()
                        .HasForeignKey("SourceTurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemoryService.Core.Domain.MemoryEdge", b =>
                {
                    b.HasOne("MemoryService.Core.Domain.Memory", null)
                        .WithMany()
                        .HasForeignKey("DstMemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MemoryService.Core.Domain.Memory", null)
                        .WithMany()
                        .HasForeignKey("SrcMemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MemoryService.Core.Domain.Turn", b =>
                {
                    b.HasOne("MemoryService.Core.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
